# Generated by Django 5.1.3 on 2024-11-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionpoint",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
