# Generated by Django 5.1.3 on 2024-11-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoApp", "0002_positionpoint_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.ImageField(upload_to="images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="positionpoint",
            name="DetailData",
        ),
        migrations.RemoveField(
            model_name="positionpoint",
            name="image",
        ),
        migrations.RemoveField(
            model_name="positionpoint",
            name="image_location",
        ),
        migrations.AddField(
            model_name="positionpoint",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="positionpoint",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="points", to="djangoApp.image"
            ),
        ),
        migrations.DeleteModel(
            name="DetailData",
        ),
    ]
