# Generated by Django 5.1.3 on 2024-11-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoApp", "0003_image_remove_positionpoint_detaildata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("type1", "Type 1"),
                            ("type2", "Type 2"),
                            ("type3", "Type 3"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "result",
                    models.FileField(blank=True, null=True, upload_to="task_results/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
