# Generated by Django 5.1.3 on 2024-11-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoApp", "0005_remove_task_result_task_results"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("土壤去除", "Type 1"),
                    ("特征选取", "Type 2"),
                    ("type3", "Type 3"),
                ],
                max_length=50,
            ),
        ),
    ]
